<h1>ISSN Finder.</h1>
<h3>This job finds all ISSN and calls the LinkedDataWrapper for each of them.</h3>
<p>Nr of ISSN:
<!--    --><?php //echo print_r(count($this->listOfIssn), true) ?>
</p>

<p>
    <a class="button" id="issnfinder-button">Start</a>
</p>

<script type="text/javascript">
<!--encode the list of issn to a json element to make it usable via jQuery-->
//var listOfIssn = <?php //echo json_encode($this->listOfIssn); ?>//;
</script>